### ISSUE TITLE
If the procfwk.PipelineParameters.ParameterValue column in the metadata has a value of NULL, no parameters are sent to the pipeline.

### ISSUE THREAD

**Issue by jamclaug** [mrpaulandrew/ADF.procfwk#13]
If a parameter exists in the metadata, but the procfwk.PipelineParameters.ParameterValue column is NULL, then no parameters will be sent to that pipeline.

This affects the execution of worker pipelines in data factory.

1. Create a pipeline with more than one parameter.
2. Change the value of one parameter in the procfwk.PipelineParameters table to NULL, but leave the pipeline in place.
3. Execute the pipeline.

I would expect one of two outcomes:
Null parameters are simply not passed to the pipeline.
A constraint on the procfwk.PipelineParameters.ParameterValue column would prevent NULLs.

**Comment by mrpaulandrew** [comment]
Thank James, nice catch. 

What behaviour makes most sense here?...
- Not passing NULL's could lead someone to thinking there is an issue with the metadata if we simply exclude them with a where clause.
- Adding a constraint on the table then limits the parameter in the metadata being overwritten at runtime by something else. I know a couple of solutions where this is done by the Grandparent pipeline and reset to NULL post execution.

I'm wondering if its better to simply resolve a NULL parameter value to an empty string. This way behaviour in the Worker pipeline can evaluate if this is correct. This way the framework handling is fairly nature and the value being correct or not falls to the Work to access.

There is also a wider disconnect here because a parameter name isn't actually validated by the pipeline.

What are your thoughts?

Cheers

Paul

**Comment by mrpaulandrew** [comment]
@jamclaug see comment above please. If happy I'll do another interim release for this small update. Thanks

**Comment by jamclaug** [comment]
If I put a NULL parameter into a pipeline, I usually would expect the default value for that parameter to be used.  This could be configurable as a Parameter perhaps,  SendNullParameterAsEmptyString.  

As far as validating parameter names, that would certainly help catch metadata errors.

**Comment by mrpaulandrew** [comment]
Yes, good point. We really need a database NULL to be passed as NULL to Data Factory otherwise the default pipeline param will get ignored. I'll have a further play around with this.

**Comment by mrpaulandrew** [comment]
Hi @jamclaug I've had a play and ADF doesn't actually allow NULL values to be passed for a pipeline parameter. To get it to use a default value you have to avoid passing anything. Parameter name and value.

I've therefore added a case statement to the database proc to exclude the key/value pair completely if the value is NULL...

SELECT @Json += 
CASE
WHEN [ParameterValue] IS NULL THEN ''
ELSE '"' + [ParameterName] + '": "' + STRING_ESCAPE([ParameterValue],'json') + '",'
END

This means the pipeline default will be used. Or, if NULL in the database and no default in ADF a natural error will be returned about the missing value.

I'll release this update early next week.

Thanks again
